language: node_js
node_js:
  - 'stable'
  - '9'
  - '8'
  - '7'
  - '6'

sudo: false

matrix:
  fast_finish: true

branches:
  only:
    - feature/10

cache:
  directories:
    - node_modules
git:
  depth: false

jobs:
  include:
    - stage: install
      script: npm install
    - stage: test
      script: npm run cover
