language: node_js

node_js:
  - '10'
  # - '9'
  # - '8'
  # - '7'
  # - '6'

sudo: false

matrix:
  fast_finish: true

addons:
  sonarcloud:
    organization: "pjpimentel-github"

branches:
  only:
    - beta

install:
  - npm install

script:
  - npm test
  - npm run build
  - sonar-scanner

cache:
  directories:
    - node_modules

git:
  depth: false
