language: node_js

sudo: false

matrix:
  fast_finish: true

addons:
  sonarcloud:
    organization: "pjpimentel-github"

branches:
  only:
    - beta

install:
  - npm install

cache:
  directories:
    - node_modules
    - '$HOME/.sonar/cache'

git:
  depth: false

env:
  global:
  - GH_REPO="https://${GH_TOKEN}@github.com/pjpimentel/dots.git"

stages:
  - build
  - test
  - quality check
  - deploy

jobs:
 include:
    - stage: build
      script: npm run build
      node_js: '10'
    # - stage: build
    #   script: npm run build
    #   node_js: '9'
    # - stage: build
    #   script: npm run build
    #   node_js: '8'
    # - stage: build
    #   script: npm run build
    #   node_js: '7'
    # - stage: build
    #   script: npm run build
    #   node_js: '6'
    - stage: test
      script: npm run test:unit
      node_js: '10'
    # - stage: test
    #   script: npm run test:unit
    #   node_js: '9'
    # - stage: test
    #   script: npm run test:unit
    #   node_js: '8'
    # - stage: test
    #   script: npm run test:unit
    #   node_js: '7'
    # - stage: test
    #   script: npm run test:unit
    #   node_js: '6'
    - stage: quality check
      node_js: '10'
      script:
        - npm run test:coverage
        - sonar-scanner
    - stage: npm release
      node_js: '10'
      if: branch = beta
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - |
            PACKAGE_VERSION=$(cat package.json |\
            grep version |\
            head -1 |\
            awk -F: '{ print $2 }' |\
            sed 's/[",]//g' |\
            tr -d '[[:space:]]')
        - TAG=v$PACKAGE_VERSION-$TRAVIS_COMMIT
        - git tag $TAG -m "[ci] git tag ${TAG}"
        - npm version from-git -m "[ci] npm version ${TAG}"
        - git checkout -b $TRAVIS_BRANCH
        - git add package*.json
        - git commit --message "[ci] travis build $TRAVIS_BUILD_NUMBER"
        - git remote add origin $GH_REPO
        - git push origin $TAG
        - git push origin beta
        # - npm publish --tag beta
  # include:
  #   - stage: npm release
  #     node_js: '10'
  #     script:
  #     deploy:
  #       provider: npm
  #       api_key: $NPM_API_KEY
  #       on: deploy-npm-release
