language: node_js

sudo: false

matrix:
  fast_finish: true

addons:
  sonarcloud:
    organization: "pjpimentel-github"

branches:
  only:
    - beta

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: false

stages:
  - build
  - test
  - quality check
  - deploy

jobs:
 include:
    - stage: build
      script: npm run build
      node_js: '10'
    - stage: build
      script: npm run build
      node_js: '9'
    - stage: build
      script: npm run build
      node_js: '8'
    - stage: build
      script: npm run build
      node_js: '7'
    - stage: build
      script: npm run build
      node_js: '6'
    - stage: test
      script: npm run test:unit
      node_js: '10'
    - stage: test
      script: npm run test:unit
      node_js: '9'
    - stage: test
      script: npm run test:unit
      node_js: '8'
    - stage: test
      script: npm run test:unit
      node_js: '7'
    - stage: test
      script: npm run test:unit
      node_js: '6'
    - stage: quality check
      node_js: '10'
      script:
        - npm run test:coverage
        - sonar-scanner
    - stage: npm release
      node_js: '10'
      script: echo "deploying..."
  # include:
  #   - stage: npm release
  #     node_js: '10'
  #     script:
  #     deploy:
  #       provider: npm
  #       api_key: $NPM_API_KEY
  #       on: deploy-npm-release
