language: node_js

node_js:
  - 'latest'
  - 'stable'
  - '7'
  - '6'

sudo: false

matrix:
  fast_finish: true

branches:
  only:
    - feature/10

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: false
